version: "3.8"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./server
        target: /app
    ports:
      - 3000:8080
