"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var _a = require("../controllers/tasks"), createTask = _a.createTask, modifyTask = _a.modifyTask, removeTask = _a.removeTask, moveTask = _a.moveTask;
var tasksRouter = express_1.Router();
tasksRouter.post("/", createTask);
tasksRouter.patch("/", modifyTask);
tasksRouter.patch("/move", moveTask);
tasksRouter.delete("/", removeTask);
exports.default = tasksRouter;
